/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8hMgcIqUo39
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function landingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 shadow">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CalendarIcon className="h-6 w-6" />
            <span className="text-xl font-bold">Impactify</span>
          </Link>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Events
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Partners
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Analytics
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Tickets
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Messaging
            </Link>
          </nav>
          <Button variant="secondary">Create Event</Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter md:text-4xl">Effortless Event Management</h1>
                <p className="text-muted-foreground md:text-xl">
                  Impactify is your all-in-one solution for creating, managing, and analyzing successful events.
                </p>
                <div className="flex flex-col sm:flex-row gap-2">
                  <Button>Create Event</Button>
                  <Button variant="outline">Learn More</Button>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Event Management"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Partner Marketplace"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="space-y-4">
                <h2 className="text-2xl font-bold tracking-tighter md:text-3xl">Discover the Perfect Partners</h2>
                <p className="text-muted-foreground md:text-xl">
                  Impactify's Partner Marketplace connects you with vetted vendors, venues, and other event
                  professionals to make your events a success.
                </p>
                <Button>Explore Partners</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold tracking-tighter md:text-3xl">Insightful Event Analytics</h2>
                <p className="text-muted-foreground md:text-xl">
                  Gain valuable insights into your event performance with Impactify's comprehensive analytics and
                  reporting tools.
                </p>
                <Button>View Analytics</Button>
              </div>
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Event Analytics"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Booking and Ticketing"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
              <div className="space-y-4">
                <h2 className="text-2xl font-bold tracking-tighter md:text-3xl">Seamless Booking and Ticketing</h2>
                <p className="text-muted-foreground md:text-xl">
                  Impactify's integrated ticketing and registration system makes it easy to manage event registrations
                  and payments.
                </p>
                <Button>Explore Ticketing</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-12">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold tracking-tighter md:text-3xl">
                  Streamlined Messaging and Collaboration
                </h2>
                <p className="text-muted-foreground md:text-xl">
                  Impactify's messaging and collaboration tools help you coordinate with partners, vendors, and
                  attendees for a seamless event experience.
                </p>
                <Button>Explore Messaging</Button>
              </div>
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Messaging and Collaboration"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6">
        <div className="container mx-auto px-4 md:px-6 flex items-center justify-between">
          <p className="text-sm">&copy; 2024 Impactify. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}
