/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YcoZa7rQb5H
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"

export function loginPage() {
  return (
    <div className="flex min-h-screen">
      <div className="flex flex-col justify-center w-full max-w-md p-8 space-y-8 bg-white">
        <div className="flex items-center space-x-2">
          <h1 className="text-2xl font-bold">Impactify</h1>
        </div>
        <div>
          <h2 className="text-3xl font-bold">Welcome back</h2>
          <p className="mt-2 text-muted-foreground">Continue with Google or enter your details.</p>
        </div>
        <Button variant="outline" className="w-full">
          <ChromeIcon className="w-5 h-5 mr-2" />
          Log in with Google
        </Button>
        <div className="flex items-center my-4">
          <hr className="flex-1" />
          <span className="px-2 text-sm text-muted-foreground">or</span>
          <hr className="flex-1" />
        </div>
        <form className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" placeholder="Enter your password" type="password" />
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Checkbox id="remember" />
              <Label htmlFor="remember" className="text-sm">
                Remember for 30 days
              </Label>
            </div>
            <Link href="#" className="text-sm text-muted-foreground" prefetch={false}>
              Forgot password
            </Link>
          </div>
          <Button className="w-full">Log in</Button>
        </form>
        <div className="text-sm text-center">
          Don't have an account?{" "}
          <Link href="#" className="font-semibold" prefetch={false}>
            Sign up for free
          </Link>
        </div>
      </div>
      <div
        className="relative flex-1 bg-cover bg-center"
        style={{ backgroundImage: "url('/placeholder.svg?height=800&width=800')" }}
      >
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="text-white">
            <LogInIcon className="w-16 h-16" />
            <h1 className="mt-4 text-4xl font-bold">Untitled UI</h1>
          </div>
        </div>
      </div>
    </div>
  )
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}


function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}
